### PR TITLE
Update config-set() and config-reset() to respect $config-manger-variables

### PR DESCRIPTION
**Pull request by lolmaus**

### CODE REVIEW

**Comment by lolmaus** [comment]
LOL, you deleted my branch, but our app depended on it, so our build broke. :)

We updated to depend on `sass-projects/sass-config-manager#develop` while waiting for a release.

**Comment by prisis** [comment]
Ah im so sorry!!!, in still need a better idea for this. The test failing because of this change...

**Comment by lolmaus** [comment]
I'll try to look into tests tomorrow.

**Comment by lolmaus** [comment]
Uhm, did you revert all the global-local stuff?

**Comment by prisis** [comment]
I changed all var to global. I make now a new reales. It should work for you and all others.

**Comment by lolmaus** [comment]
Uhm... Do you mean that the change back to global is temporary?

**Comment by prisis** [comment]
No, it now remains so.

**Comment by lolmaus** [comment]
But then it won't work for me.

**Comment by prisis** [comment]
the problem is, that if we change set and reset, no to use global var, it wont work..

**Comment by lolmaus** [comment]
But this PR we're commenting on now -- it has set and reset use global conditionally and it does work?

**Comment by prisis** [comment]
If you check the master or develop branch all test are green, now you need to test if it works for you.

**Comment by lolmaus** [comment]
My goal is to not have anything in the global scope -- just like in JS strict mode.

**Comment by prisis** [comment]
Ah.. but the set and reset wont work without the global hack...

**Comment by lolmaus** [comment]
Let me ask again: why did this PR not work for you? E. g.:

``` js
      @if ($config-manger-variables == 'global') {
        $config-default: map-remove($config-default, $setting) !global;
      } @else {
        $config-default: map-remove($config-default, $setting);
      }
```

**Comment by prisis** [comment]
if i run the test with this.

```
$config-default: map-remove($config-default, $setting);
```

im only get errors. Because all vars are empty.

**Comment by lolmaus** [comment]
Uhm... Isn't it obvious that the local scenario needs a different test setup than the global one?

I didn't look into tests because you said you got them done, but I can.

**Comment by prisis** [comment]
Please, do so.

**Comment by lolmaus** [comment]
1. Will you revert to the `$config-manger-variables` approach if I manage to fix the tests?
2. Which commit should I work from? (the last commit with `$config-manger-variables`)

**Comment by prisis** [comment]
1. Yes i do :)
2. From develop.

**Comment by lolmaus** [comment]
Looks like ba70cddf15 is the last commit that has `$config-manger-variables`.

But there are not broken tests. What should I look for?

**Comment by prisis** [comment]
They only brock if you make changes on set and rest.

```
@if ($config-manger-variables == 'global') {
        $config-default: map-remove($config-default, $setting) !global;
} @else {
        $config-default: map-remove($config-default, $setting);
}
```

**Pull request merged**
